services:
  - type: web
    name: icta-attachees
    plan: free
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn attachees.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: icta-attachees-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
databases:
  - name: icta-attachees-db
    plan: free
