# Generated by Django 6.0.5 on 2026-06-10 08:48

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, null=True, upload_to=core.models.report_upload_path)),
                ('report_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('report_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Cleared / Passed'), ('REJECTED', 'Rejected / Re-upload Required')], default='PENDING', max_length=15)),
                ('evaluation_file', models.FileField(blank=True, null=True, upload_to=core.models.evaluation_upload_path)),
                ('evaluation_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('examiner_remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_assessment', to='core.attacheeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('monday_activities', models.TextField(blank=True, help_text='Log daily tasks completed on Monday', null=True)),
                ('tuesday_activities', models.TextField(blank=True, help_text='Log daily tasks completed on Tuesday', null=True)),
                ('wednesday_activities', models.TextField(blank=True, help_text='Log daily tasks completed on Wednesday', null=True)),
                ('thursday_activities', models.TextField(blank=True, help_text='Log daily tasks completed on Thursday', null=True)),
                ('friday_activities', models.TextField(blank=True, help_text='Log daily tasks completed on Friday', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Signed Off / Approved'), ('REVISION', 'Requires Revision')], default='PENDING', max_length=15)),
                ('supervisor_remarks', models.TextField(blank=True, help_text='Feedback or critique from your supervisor', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='core.attacheeprofile')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('attachee', 'week_start_date')},
            },
        ),
    ]
