# Generated by Django 6.0.5 on 2026-06-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_finalassessment_weeklylog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together={('attachee', 'week_start_date', 'assigned_day')},
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='work_mode',
            field=models.CharField(choices=[('PHYSICAL', 'On-Site Reporting Active'), ('REMOTE', 'Remote Work Active')], default='REMOTE', max_length=15),
        ),
    ]
