# Generated by Django 6.0.5 on 2026-06-11 08:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shiftassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'verbose_name': 'Weekly Roster', 'verbose_name_plural': 'Weekly Rosters'},
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together={('attachee', 'week_start_date')},
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='friday_physical',
            field=models.BooleanField(default=False, verbose_name='Friday (On-Site)'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='monday_physical',
            field=models.BooleanField(default=False, verbose_name='Monday (On-Site)'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='thursday_physical',
            field=models.BooleanField(default=False, verbose_name='Thursday (On-Site)'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='tuesday_physical',
            field=models.BooleanField(default=False, verbose_name='Tuesday (On-Site)'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='wednesday_physical',
            field=models.BooleanField(default=False, verbose_name='Wednesday (On-Site)'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='week_start_date',
            field=models.DateField(help_text='Select the Monday of the target roster week.'),
        ),
        migrations.CreateModel(
            name='RosterPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('FIXED', 'Fixed Weekly Days (e.g., every Mon/Wed)'), ('ROTATING_2X2', 'Alternating Blocks (2 Days On-Site, 2 Days Remote)'), ('INTERVAL', 'Custom Intermittent Frequency (Every X Days)')], default='FIXED', max_length=20)),
                ('mon_on_site', models.BooleanField(default=False, verbose_name='Repeat Mondays')),
                ('tue_on_site', models.BooleanField(default=False, verbose_name='Repeat Tuesdays')),
                ('wed_on_site', models.BooleanField(default=False, verbose_name='Repeat Wednesdays')),
                ('thu_on_site', models.BooleanField(default=False, verbose_name='Repeat Thursdays')),
                ('fri_on_site', models.BooleanField(default=False, verbose_name='Repeat Fridays')),
                ('custom_interval_days', models.IntegerField(default=1, help_text='e.g., Enter 3 for every 3rd day physical shift')),
                ('policy_start_date', models.DateField(default=datetime.date.today, help_text='The date this automated rotation rule begins')),
                ('attachee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roster_policy', to='core.attacheeprofile')),
            ],
            options={
                'verbose_name': 'Roster Generation Policy',
                'verbose_name_plural': 'Roster Generation Policies',
            },
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='assigned_day',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='work_mode',
        ),
    ]
