# Generated by Django 6.0.5 on 2026-06-11 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_shiftassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Select the Monday date of the target roster week.')),
                ('generation_mode', models.CharField(choices=[('MANUAL', 'Manual Day Selection (Use Checkboxes Below)'), ('CONSECUTIVE_2', '2 Days On-Site / 2 Days Remote (Continuous)'), ('CONSECUTIVE_3', '3 Days On-Site / 3 Days Remote (Continuous)'), ('INTERVAL_2', 'Alternate Days (Every 2nd Day On-Site)'), ('INTERVAL_3', 'Intermittent Tracking (Every 3rd Day On-Site)')], default='MANUAL', max_length=20, verbose_name='Roster Generation Pattern/Range')),
                ('monday_physical', models.BooleanField(default=False, verbose_name='Monday (On-Site)')),
                ('tuesday_physical', models.BooleanField(default=False, verbose_name='Tuesday (On-Site)')),
                ('wednesday_physical', models.BooleanField(default=False, verbose_name='Wednesday (On-Site)')),
                ('thursday_physical', models.BooleanField(default=False, verbose_name='Thursday (On-Site)')),
                ('friday_physical', models.BooleanField(default=False, verbose_name='Friday (On-Site)')),
                ('attachee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_rostering', to='core.attacheeprofile')),
            ],
            options={
                'verbose_name': 'Weekly Roster',
                'verbose_name_plural': 'Weekly Rosters',
                'unique_together': {('attachee', 'week_start_date')},
            },
        ),
    ]
