# Generated by Django 6.0.5 on 2026-06-11 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_weeklyroster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttacheeRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_mode', models.CharField(choices=[('MANUAL', 'Custom Days Selection (Check below)'), ('CONSTANT', 'Constant On-Site (All 5 Days)'), ('CONSECUTIVE_1', '1 Day On-Site (Mon)'), ('CONSECUTIVE_2', '2 Days On-Site (Mon-Tue)'), ('CONSECUTIVE_3', '3 Days On-Site (Mon-Wed)'), ('CONSECUTIVE_4', '4 Days On-Site (Mon-Thu)')], default='MANUAL', max_length=20, verbose_name='Weekly Schedule Rule')),
                ('monday_physical', models.BooleanField(default=False, verbose_name='Monday On-Site')),
                ('tuesday_physical', models.BooleanField(default=False, verbose_name='Tuesday On-Site')),
                ('wednesday_physical', models.BooleanField(default=False, verbose_name='Wednesday On-Site')),
                ('thursday_physical', models.BooleanField(default=False, verbose_name='Thursday On-Site')),
                ('friday_physical', models.BooleanField(default=False, verbose_name='Friday On-Site')),
                ('attachee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_roster', to='core.attacheeprofile')),
            ],
            options={
                'verbose_name': 'Permanent Attachée Roster',
                'verbose_name_plural': 'Permanent Attachée Rosters',
            },
        ),
        migrations.DeleteModel(
            name='WeeklyRoster',
        ),
    ]
