# Generated by Django 6.0.5 on 2026-06-13 17:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attacheeroster_delete_weeklyroster'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_name', models.CharField(max_length=15)),
                ('work_mode', models.CharField(choices=[('PHYSICAL', 'On-Site'), ('REMOTE', 'Remote')], max_length=15)),
                ('attachee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_shifts', to='core.attacheeprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('attachee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RosterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_mode', models.CharField(choices=[('CONSTANT', 'Constant Fixed Days (Select Days Below)'), ('INTERVAL_1', '1 Day Gap (On-Site, 1 Day Remote, On-Site...)'), ('INTERVAL_2', '2 Days Gap (On-Site, 2 Days Remote, On-Site...)'), ('INTERVAL_3', '3 Days Gap (On-Site, 3 Days Remote, On-Site...)'), ('INTERVAL_4', '4 Days Gap (On-Site, 4 Days Remote, On-Site...)')], default='CONSTANT', max_length=20, verbose_name='Scheduling Pattern Rule')),
                ('constant_monday', models.BooleanField(default=False, verbose_name='Constant Monday')),
                ('constant_tuesday', models.BooleanField(default=False, verbose_name='Constant Tuesday')),
                ('constant_wednesday', models.BooleanField(default=False, verbose_name='Constant Wednesday')),
                ('constant_thursday', models.BooleanField(default=False, verbose_name='Constant Thursday')),
                ('constant_friday', models.BooleanField(default=False, verbose_name='Constant Friday')),
                ('rotation_start_date', models.DateField(default=datetime.date.today, help_text='The first day the rolling sequence logic begins calculations.', verbose_name='Rotation Anchor Start Date')),
                ('attachee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roster_config', to='core.attacheeprofile')),
            ],
            options={
                'verbose_name': 'Roster Configuration',
                'verbose_name_plural': 'Roster Configurations',
            },
        ),
        migrations.DeleteModel(
            name='AttacheeRoster',
        ),
    ]
