# Generated by Django 6.0.5 on 2026-06-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_generatedshift_rosterconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'verbose_name': 'Shift Assignment', 'verbose_name_plural': 'Shift Assignments'},
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='assigned_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='work_mode',
            field=models.CharField(choices=[('PHYSICAL', 'On-Site Reporting Active'), ('REMOTE', 'Remote Work Active')], default='REMOTE', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together={('attachee', 'week_start_date', 'assigned_day')},
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='week_start_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='RosterPolicy',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='friday_physical',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='monday_physical',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='thursday_physical',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='tuesday_physical',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='wednesday_physical',
        ),
    ]
