# Generated by Django 6.0.5 on 2026-06-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_shiftassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacheeprofile',
            name='attachment_end_date',
            field=models.DateField(blank=True, help_text='End date of industrial attachment', null=True),
        ),
        migrations.AddField(
            model_name='attacheeprofile',
            name='attachment_start_date',
            field=models.DateField(blank=True, help_text='Start date of industrial attachment', null=True),
        ),
    ]
