# Generated by Django 6.0.6 on 2026-06-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_attachment_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_work_mode',
            field=models.CharField(choices=[('ALL', 'Overall - All Attachées in Department'), ('REMOTE', 'Remote Attachées Only'), ('PHYSICAL', 'Office / In-Person Attachées Only')], default='ALL', max_length=15),
        ),
    ]
