# Generated by Django 6.0.5 on 2026-06-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_target_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacheeprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
