# Generated by Django 6.0.5 on 2026-06-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_attacheeprofile_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rosterconfiguration',
            name='attachee',
        ),
        migrations.AddField(
            model_name='rosterconfiguration',
            name='attachees',
            field=models.ManyToManyField(related_name='roster_configs', to='core.attacheeprofile'),
        ),
        migrations.AlterField(
            model_name='attacheeprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Waiting to Start)'), ('ACTIVE', 'Active on Program'), ('COMPLETED', 'Attachment Finished'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
