# Generated by Django 6.0.6 on 2026-07-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacheeprofile',
            name='status',
            field=models.CharField(choices=[('PENDING_HR', 'Pending HR Approval'), ('PENDING', 'Pending Supervisor Approval'), ('APPROVED', 'Approved (Waiting to Start)'), ('ACTIVE', 'Active on Program'), ('COMPLETED', 'Attachment Finished'), ('REJECTED', 'Rejected')], default='PENDING_HR', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('SUPERVISOR', 'Department Supervisor'), ('ATTACHEE', 'ICT Attachée'), ('HR', 'Human Resources Officer')], default='ATTACHEE', max_length=20),
        ),
    ]
