# Generated by Django 6.0.6 on 2026-07-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_attacheeprofile_status_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacheeprofile',
            name='certificate_approved',
            field=models.BooleanField(default=False),
        ),
    ]
