# Generated by Django 6.0.6 on 2026-07-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_attacheeprofile_certificate_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_suffix', models.CharField(help_text='Suffix that every new attachée username must end with. E.g.  /026', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration Configuration',
                'verbose_name_plural': 'Registration Configurations',
            },
        ),
    ]
