# A list of public and private universities and colleges in Kenya
# This can be expanded over time.

KENYAN_INSTITUTIONS = [
    ('', '--------- Select Your Institution ---------'),
    ('Africa International University', 'Africa International University'),
    ('Africa Nazarene University', 'Africa Nazarene University'),
    ('Aga Khan University', 'Aga Khan University'),
    ('Amref International University', 'Amref International University'),
    ('Bomet University College', 'Bomet University College'),
    ('Chuka University', 'Chuka University'),
    ('Co-operative University of Kenya', 'Co-operative University of Kenya'),
    ('Daystar University', 'Daystar University'),
    ('Dedan Kimathi University of Technology', 'Dedan Kimathi University of Technology'),
    ('Egerton University', 'Egerton University'),
    ('Garissa University', 'Garissa University'),
    ('Great Lakes University of Kisumu', 'Great Lakes University of Kisumu'),
    ('Gretsa University', 'Gretsa University'),
    ('Jaramogi Oginga Odinga University of Science and Technology', 'Jaramogi Oginga Odinga University of Science and Technology'),
    ('Jomo Kenyatta University of Agriculture and Technology', 'Jomo Kenyatta University of Agriculture and Technology'),
    ('Kabarak University', 'Kabarak University'),
    ('Kaimosi Friends University', 'Kaimosi Friends University'),
    ('Karatina University', 'Karatina University'),
    ('KCA University', 'KCA University'),
    ('Kenya Highlands Evangelical University', 'Kenya Highlands Evangelical University'),
    ('Kenya Methodist University', 'Kenya Methodist University'),
    ('Kenyatta University', 'Kenyatta University'),
    ('Kiriri Womens University of Science and Technology', 'Kiriri Womens University of Science and Technology'),
    ('Kisii University', 'Kisii University'),
    ('Koitaleel Samoei University College', 'Koitaleel Samoei University College'),
    ('Laikipia University', 'Laikipia University'),
    ('Lukenya University', 'Lukenya University'),
    ('Machakos University', 'Machakos University'),
    ('Maasai Mara University', 'Maasai Mara University'),
    ('Maseno University', 'Maseno University'),
    ('Masinde Muliro University of Science and Technology', 'Masinde Muliro University of Science and Technology'),
    ('Meru University of Science and Technology', 'Meru University of Science and Technology'),
    ('Moi University', 'Moi University'),
    ('Mombasa Technical University', 'Mombasa Technical University'),
    ('Mount Kenya University', 'Mount Kenya University'),
    ('Multimedia University of Kenya', 'Multimedia University of Kenya'),
    ('Muranga University of Technology', 'Muranga University of Technology'),
    ('Pan Africa Christian University', 'Pan Africa Christian University'),
    ('Pwani University', 'Pwani University'),
    ('Riara University', 'Riara University'),
    ('Rongo University', 'Rongo University'),
    ('Scott Christian University', 'Scott Christian University'),
    ('South Eastern Kenya University', 'South Eastern Kenya University'),
    ('St. Pauls University', 'St. Pauls University'),
    ('Strathmore University', 'Strathmore University'),
    ('Taita Taveta University', 'Taita Taveta University'),
    ('Technical University of Kenya', 'Technical University of Kenya'),
    ('Tharaka University', 'Tharaka University'),
    ('The East African University', 'The East African University'),
    ('Tom Mboya University', 'Tom Mboya University'),
    ('Turkana University College', 'Turkana University College'),
    ('United States International University Africa', 'United States International University Africa'),
    ('University of Eastern Africa, Baraton', 'University of Eastern Africa, Baraton'),
    ('University of Embu', 'University of Embu'),
    ('University of Kabianga', 'University of Kabianga'),
    ('University of Nairobi', 'University of Nairobi'),
    ('Uzima University', 'Uzima University'),
    ('Zetech University', 'Zetech University'),
    # Technical and Vocational Colleges
    ('Baringo Technical College', 'Baringo Technical College'),
    ('Bureti Technical and Vocational College', 'Bureti Technical and Vocational College'),
    ('Eldoret National Polytechnic', 'Eldoret National Polytechnic'),
    ('Kabete National Polytechnic', 'Kabete National Polytechnic'),
    ('Kenya Coast National Polytechnic', 'Kenya Coast National Polytechnic'),
    ('Kenya Technical Trainers College', 'Kenya Technical Trainers College'),
    ('Kisii National Polytechnic', 'Kisii National Polytechnic'),
    ('Kisumu National Polytechnic', 'Kisumu National Polytechnic'),
    ('Kitale National Polytechnic', 'Kitale National Polytechnic'),
    ('Meru National Polytechnic', 'Meru National Polytechnic'),
    ('North Eastern Province National Polytechnic', 'North Eastern Province National Polytechnic'),
    ('Nyeri National Polytechnic', 'Nyeri National Polytechnic'),
    ('Rift Valley Technical Training Institute', 'Rift Valley Technical Training Institute'),
    ('Sigalagala National Polytechnic', 'Sigalagala National Polytechnic'),
    # Other notable colleges
    ('Cooperative College of Kenya', 'Cooperative College of Kenya'),
    ('Kenya Institute of Management', 'Kenya Institute of Management'),
    ('Kenya Institute of Mass Communication', 'Kenya Institute of Mass Communication'),
    ('Kenya Medical Training College', 'Kenya Medical Training College'),
    ('Railway Training Institute', 'Railway Training Institute'),
    ('Utalii College', 'Utalii College'),
]