# A list of public and private universities and colleges in Kenya
# This can be expanded over time.

KENYAN_INSTITUTIONS = [
    ('', '--------- Select Your Institution ---------'),
    ('Adventist University of Africa', 'Adventist University of Africa'),
    ('Africa International University', 'Africa International University'),
    ('Africa Nazarene University', 'Africa Nazarene University'),
    ('Aga Khan University', 'Aga Khan University'),
    ('Alupe University', 'Alupe University'),
    ('Amref International University', 'Amref International University'),
    ('Baringo Technical College', 'Baringo Technical College'),
    ('Bomet University', 'Bomet University'),
    ('Bomet University College', 'Bomet University College'),
    ('Bureti Technical and Vocational College', 'Bureti Technical and Vocational College'),
    ('Catholic University of Eastern Africa', 'Catholic University of Eastern Africa'),
    ('Chuka University', 'Chuka University'),
    ('Co-operative University of Kenya', 'Co-operative University of Kenya'),
    ('Consolata International University', 'Consolata International University'),
    ('Cooperative College of Kenya', 'Cooperative College of Kenya'),
    ('Daystar University', 'Daystar University'),
    ('Dedan Kimathi University of Technology', 'Dedan Kimathi University of Technology'),
    ('East Kenya Integrated University', 'East Kenya Integrated University'),
    ('Egerton University', 'Egerton University'),
    ('Eldoret National Polytechnic', 'Eldoret National Polytechnic'),
    ('Garissa University', 'Garissa University'),
    ('Great Lakes University of Kisumu', 'Great Lakes University of Kisumu'),
    ('Gretsa University', 'Gretsa University'),
    ('Hekima University College', 'Hekima University College'),
    ('International Leadership University', 'International Leadership University'),
    ('Islamic University of Kenya', 'Islamic University of Kenya'),
    ('Jaramogi Oginga Odinga University of Science and Technology', 'Jaramogi Oginga Odinga University of Science and Technology'),
    ('Jomo Kenyatta University of Agriculture and Technology', 'Jomo Kenyatta University of Agriculture and Technology'),
    ('KAG EAST University', 'KAG EAST University'),
    ('KCA University', 'KCA University'),
    ('Kabarak University', 'Kabarak University'),
    ('Kabarnet University College', 'Kabarnet University College'),
    ('Kabete National Polytechnic', 'Kabete National Polytechnic'),
    ('Kaimosi Friends University', 'Kaimosi Friends University'),
    ('Karatina University', 'Karatina University'),
    ('Kenya Advanced Institute of Science and Technology', 'Kenya Advanced Institute of Science and Technology'),
    ('Kenya Coast National Polytechnic', 'Kenya Coast National Polytechnic'),
    ('Kenya Highlands Evangelical University', 'Kenya Highlands Evangelical University'),
    ('Kenya Institute of Management', 'Kenya Institute of Management'),
    ('Kenya Institute of Mass Communication', 'Kenya Institute of Mass Communication'),
    ('Kenya Medical Training College', 'Kenya Medical Training College'),
    ('Kenya Methodist University', 'Kenya Methodist University'),
    ('Kenya Technical Trainers College', 'Kenya Technical Trainers College'),
    ('Kenyatta University', 'Kenyatta University'),
    ('Kibabii University', 'Kibabii University'),
    ('Kirinyaga University', 'Kirinyaga University'),
    ('Kiriri Women\'s University of Science and Technology', 'Kiriri Women\'s University of Science and Technology'),
    ('Kiriri Womens University of Science and Technology', 'Kiriri Womens University of Science and Technology'),
    ('Kisii National Polytechnic', 'Kisii National Polytechnic'),
    ('Kisii University', 'Kisii University'),
    ('Kisumu National Polytechnic', 'Kisumu National Polytechnic'),
    ('Kitale National Polytechnic', 'Kitale National Polytechnic'),
    ('Koitaleel Samoei University College', 'Koitaleel Samoei University College'),
    ('Koitalel Samoei University College', 'Koitalel Samoei University College'),
    ('Laikipia University', 'Laikipia University'),
    ('Lukenya University', 'Lukenya University'),
    ('Maasai Mara University', 'Maasai Mara University'),
    ('Machakos University', 'Machakos University'),
    ('Makueni University College', 'Makueni University College'),
    ('Mama Ngina University College', 'Mama Ngina University College'),
    ('Management University of Africa', 'Management University of Africa'),
    ('Marist International University College', 'Marist International University College'),
    ('Maseno University', 'Maseno University'),
    ('Masinde Muliro University of Science and Technology', 'Masinde Muliro University of Science and Technology'),
    ('Meru National Polytechnic', 'Meru National Polytechnic'),
    ('Meru University of Science and Technology', 'Meru University of Science and Technology'),
    ('Moi University', 'Moi University'),
    ('Mombasa Technical University', 'Mombasa Technical University'),
    ('Mount Kenya University', 'Mount Kenya University'),
    ('Multimedia University of Kenya', 'Multimedia University of Kenya'),
    ('Murang\'a University of Technology', 'Murang\'a University of Technology'),
    ('Muranga University of Technology', 'Muranga University of Technology'),
    ('National Defence University-Kenya', 'National Defence University-Kenya'),
    ('National Intelligence Research University', 'National Intelligence Research University'),
    ('North Eastern Province National Polytechnic', 'North Eastern Province National Polytechnic'),
    ('Nyandarua University College', 'Nyandarua University College'),
    ('Nyeri National Polytechnic', 'Nyeri National Polytechnic'),
    ('Open University of Kenya', 'Open University of Kenya'),
    ('Outspan Global University', 'Outspan Global University'),
    ('Pan Africa Christian University', 'Pan Africa Christian University'),
    ('Pioneer International University', 'Pioneer International University'),
    ('Presbyterian University of East Africa', 'Presbyterian University of East Africa'),
    ('Pwani University', 'Pwani University'),
    ('Railway Training Institute', 'Railway Training Institute'),
    ('Riara University', 'Riara University'),
    ('Rift Valley Technical Training Institute', 'Rift Valley Technical Training Institute'),
    ('Rongo University', 'Rongo University'),
    ('Scott Christian University', 'Scott Christian University'),
    ('Sigalagala National Polytechnic', 'Sigalagala National Polytechnic'),
    ('South Eastern Kenya University', 'South Eastern Kenya University'),
    ('St. Paul\'s University', 'St. Paul\'s University'),
    ('St. Pauls University', 'St. Pauls University'),
    ('Strathmore University', 'Strathmore University'),
    ('Taita Taveta University', 'Taita Taveta University'),
    ('Tangaza University', 'Tangaza University'),
    ('Technical University of Kenya', 'Technical University of Kenya'),
    ('Technical University of Mombasa', 'Technical University of Mombasa'),
    ('Tharaka University', 'Tharaka University'),
    ('The African Talent University', 'The African Talent University'),
    ('The Co-operative University of Kenya', 'The Co-operative University of Kenya'),
    ('The East African University', 'The East African University'),
    ('Tom Mboya University', 'Tom Mboya University'),
    ('Turkana University College', 'Turkana University College'),
    ('Umma University', 'Umma University'),
    ('United States International University Africa', 'United States International University Africa'),
    ('United States International University-Africa', 'United States International University-Africa'),
    ('University of Eastern Africa, Baraton', 'University of Eastern Africa, Baraton'),
    ('University of Eldoret', 'University of Eldoret'),
    ('University of Embu', 'University of Embu'),
    ('University of Kabianga', 'University of Kabianga'),
    ('University of Nairobi', 'University of Nairobi'),
    ('Utalii College', 'Utalii College'),
    ('Uzima University', 'Uzima University'),
    ('Zetech University', 'Zetech University'),
    ('Other / Not Listed', 'Other / Not Listed'),
]
