from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models
import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver

# 1. Custom User Model for Mandatory Authentication and Roles
class User(AbstractUser):
    ROLE_CHOICES = (
        ('ADMIN', 'System Administrator'),
        ('SUPERVISOR', 'Department Supervisor'),
        ('ATTACHEE', 'ICT Attachée'),
    )
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='ATTACHEE')
    # Link supervisor users to a specific Department they manage
    department = models.ForeignKey('Department', on_delete=models.SET_NULL, null=True, blank=True, related_name='supervisors')

    def __str__(self):
        dept_info = f" - {self.department.name}" if self.department else ""
        return f"{self.username} ({self.get_role_display()}{dept_info})"


# 2. ICT Authority Departments
class Department(models.Model):
    name = models.CharField(max_length=150, unique=True)
    description = models.TextField(blank=True, null=True)
    # True for pre-loaded ICTA departments. False means it needs admin verification.
    is_verified = models.BooleanField(default=True) 

    def __str__(self):
        status = "" if self.is_verified else " (Unverified)"
        return f"{self.name}{status}"


# 3. Department Sections
class Section(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='sections')
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.department.name} - {self.name}"


# 4. Attachée Profiles (Strictly maps 1 attachée to exactly 1 department)
class AttacheeProfile(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    
    STATUS_CHOICES = (
        ('PENDING', 'Pending Approval'),
        ('APPROVED', 'Approved (Waiting to Start)'),
        ('ACTIVE', 'Active on Program'),
        ('COMPLETED', 'Attachment Finished'),
        ('REJECTED', 'Rejected'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='attachee_profile')
    full_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    national_id = models.CharField(max_length=20, unique=True, null=True, blank=True)
    registration_number = models.CharField(max_length=50, unique=True)
    course_name = models.CharField(max_length=150) # e.g., BSc. Computer Science
    institution = models.CharField(max_length=150) # e.g., Kisii University
    
    # ForeignKey ensures an attachée can ONLY belong to one department
    department = models.ForeignKey(Department, on_delete=models.PROTECT, related_name='attachees')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    # Attachment period dates
    attachment_start_date = models.DateField(null=True, blank=True, help_text="Start date of industrial attachment")
    attachment_end_date = models.DateField(null=True, blank=True, help_text="End date of industrial attachment")
    created_at = models.DateTimeField(auto_now_add=True)

    def update_status(self):
        """
        Automatically transitions status based on current date.
        PENDING/REJECTED stays as is unless manually changed.
        APPROVED -> ACTIVE when today >= start_date
        ACTIVE/APPROVED -> COMPLETED when today > end_date
        """
        from django.utils import timezone
        today = timezone.now().date()
        
        changed = False
        
        # Rule 1: Auto-complete if end date passed (highest priority)
        if self.status in ['APPROVED', 'ACTIVE'] and self.attachment_end_date:
            if today > self.attachment_end_date:
                self.status = 'COMPLETED'
                changed = True
        
        # Rule 2: Activate if start date reached and not yet completed
        if self.status == 'APPROVED' and self.attachment_start_date:
            if today >= self.attachment_start_date and today <= (self.attachment_end_date or today):
                self.status = 'ACTIVE'
                changed = True
                
        return changed

    def save(self, *args, **kwargs):
        # Trigger auto-status update before saving
        self.update_status()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.full_name} ({self.registration_number})"


# 5. Shift Assignment Table (Monday to Friday, generated by the backend engine)
# Make sure this class is defined at the root level of your core/models.py file
class ShiftAssignment(models.Model):
    DAY_CHOICES = (
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
    )
    
    MODE_CHOICES = (
        ('PHYSICAL', 'On-Site Reporting Active'),
        ('REMOTE', 'Remote Work Active'),
    )
    
    attachee = models.ForeignKey(AttacheeProfile, on_delete=models.CASCADE, related_name='shifts')
    assigned_day = models.CharField(max_length=10, choices=DAY_CHOICES)
    week_start_date = models.DateField()
    work_mode = models.CharField(max_length=15, choices=MODE_CHOICES, default='REMOTE')

    class Meta:
        unique_together = ('attachee', 'week_start_date', 'assigned_day')
        verbose_name = "Shift Assignment"
        verbose_name_plural = "Shift Assignments"

    def __str__(self):
        return f"{self.attachee.full_name} - {self.assigned_day} ({self.get_work_mode_display()}) - Week: {self.week_start_date}"
# 6. Task Board (For off-shift or remote days, posted by supervisors)
class Task(models.Model):
    TARGET_MODE_CHOICES = (
        ('ALL', 'Overall - All Attachées in Department'),
        ('REMOTE', 'Remote Attachées Only'),
        ('PHYSICAL', 'Office / In-Person Attachées Only'),
    )

    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='tasks')
    supervisor = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'role': 'SUPERVISOR'})
    title = models.CharField(max_length=200)
    description = models.TextField()
    target_work_mode = models.CharField(max_length=15, choices=TARGET_MODE_CHOICES, default='ALL')
    posted_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField()

    def __str__(self):
        return f"{self.title} - {self.department.name}"
    
from django.db import models
from django.conf import settings

class WeeklyLog(models.Model):
    STATUS_CHOICES = [
        ('PENDING', 'Pending Review'),
        ('APPROVED', 'Signed Off / Approved'),
        ('REVISION', 'Requires Revision'),
    ]

    attachee = models.ForeignKey('AttacheeProfile', on_delete=models.CASCADE, related_name='weekly_logs')
    week_start_date = models.DateField()  # The Monday date for this logbook week
    
    # Text areas for each active operational weekday record
    monday_activities = models.TextField(blank=True, null=True, help_text="Log daily tasks completed on Monday")
    tuesday_activities = models.TextField(blank=True, null=True, help_text="Log daily tasks completed on Tuesday")
    wednesday_activities = models.TextField(blank=True, null=True, help_text="Log daily tasks completed on Wednesday")
    thursday_activities = models.TextField(blank=True, null=True, help_text="Log daily tasks completed on Thursday")
    friday_activities = models.TextField(blank=True, null=True, help_text="Log daily tasks completed on Friday")
    
    # Supervisor oversight fields
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='PENDING')
    supervisor_remarks = models.TextField(blank=True, null=True, help_text="Feedback or critique from your supervisor")
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('attachee', 'week_start_date')
        ordering = ['-week_start_date']

    def __str__(self):
        return f"Log Week {self.week_start_date} - {self.attachee.full_name} ({self.status})"
    
import os

def report_upload_path(instance, filename):
    # Organizes final reports by registration number cleanly
    ext = filename.split('.')[-1]
    filename = f"Final_Report_{instance.attachee.registration_number.replace('/', '_')}.{ext}"
    return os.path.join('final_reports/', filename)

def evaluation_upload_path(instance, filename):
    # Organizes supervisor evaluation sheets safely
    ext = filename.split('.')[-1]
    filename = f"Supervisor_Evaluation_{instance.attachee.registration_number.replace('/', '_')}.{ext}"
    return os.path.join('supervisor_evaluations/', filename)

class FinalAssessment(models.Model):
    STATUS_CHOICES = [
        ('PENDING', 'Pending Review'),
        ('APPROVED', 'Cleared / Passed'),
        ('REJECTED', 'Rejected / Re-upload Required'),
    ]

    attachee = models.OneToOneField(AttacheeProfile, on_delete=models.CASCADE, related_name='final_assessment')
    # Fixed: changed upload_path to upload_to
    report_file = models.FileField(upload_to=report_upload_path, null=True, blank=True)
    report_uploaded_at = models.DateTimeField(null=True, blank=True)
    report_status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='PENDING')
    
    # Fixed: changed upload_path to upload_to
    evaluation_file = models.FileField(upload_to=evaluation_upload_path, null=True, blank=True)
    evaluation_uploaded_at = models.DateTimeField(null=True, blank=True)
    
    final_grade = models.CharField(max_length=2, blank=True, null=True) 
    examiner_remarks = models.TextField(blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        # Fixed: changed instance.attachee to self.attachee
        return f"Assessment Matrix - {self.attachee.full_name}"
    




from django.db import models
import datetime

class RosterConfiguration(models.Model):
    ROSTER_MODES = (
        ('CONSTANT', 'Constant Fixed Days (Select Days Below)'),
        ('INTERVAL_1', '1 Day Gap (On-Site, 1 Day Remote, On-Site...)'),
        ('INTERVAL_2', '2 Days Gap (On-Site, 2 Days Remote, On-Site...)'),
        ('INTERVAL_3', '3 Days Gap (On-Site, 3 Days Remote, On-Site...)'),
        ('INTERVAL_4', '4 Days Gap (On-Site, 4 Days Remote, On-Site...)'),
    )

    # Changed to ManyToManyField to allow bulk assignment
    attachees = models.ManyToManyField(
        'AttacheeProfile', 
        related_name='roster_configs'
    )
    generation_mode = models.CharField(
        max_length=20, 
        choices=ROSTER_MODES, 
        default='CONSTANT',
        verbose_name="Scheduling Pattern Rule"
    )
    
    # Used ONLY if CONSTANT mode is selected
    constant_monday = models.BooleanField(default=False, verbose_name="Constant Monday")
    constant_tuesday = models.BooleanField(default=False, verbose_name="Constant Tuesday")
    constant_wednesday = models.BooleanField(default=False, verbose_name="Constant Wednesday")
    constant_thursday = models.BooleanField(default=False, verbose_name="Constant Thursday")
    constant_friday = models.BooleanField(default=False, verbose_name="Constant Friday")
    
    # Used to anchor the rolling intervals calculation
    rotation_start_date = models.DateField(
        default=datetime.date.today, 
        verbose_name="Rotation Anchor Start Date",
        help_text="The first day the rolling sequence logic begins calculations."
    )

    class Meta:
        verbose_name = "Roster Configuration"
        verbose_name_plural = "Roster Configurations"

    def __str__(self):
        return f"Roster Rule ({self.get_generation_mode_display()}) applied to {self.attachees.count()} attachees"


class GeneratedShift(models.Model):
    attachee = models.ForeignKey('AttacheeProfile', on_delete=models.CASCADE, related_name='generated_shifts')
    date = models.DateField()
    day_name = models.CharField(max_length=15)
    work_mode = models.CharField(max_length=15, choices=(('PHYSICAL', 'On-Site'), ('REMOTE', 'Remote')))

    class Meta:
        unique_together = ('attachee', 'date')
        ordering = ['date']

    def __str__(self):
        return f"{self.attachee.full_name} - {self.date} ({self.work_mode})"
    
from django.db.models.signals import post_save
from django.dispatch import receiver

@receiver(post_save, sender=RosterConfiguration)
def execute_algorithmic_schedule(sender, instance, **kwargs):
    """
    Computes precise calendar dates for multiple attachees based on a shared rule.
    """
    # This signal now runs for each configuration. We iterate through the associated attachees.
    # Note: The m2m_changed signal is often better for ManyToMany, but post_save works for creation.
    for attachee in instance.attachees.all():
        # Wipe out future assignments to recalculate cleanly from the start date
        GeneratedShift.objects.filter(attachee=attachee, date__gte=instance.rotation_start_date).delete()
        
        start_date = instance.rotation_start_date
        shifts_to_create = []
        
        # Determine the remote gap size if an interval mode is chosen
        interval_gaps = {
            'INTERVAL_1': 1,
            'INTERVAL_2': 2,
            'INTERVAL_3': 3,
            'INTERVAL_4': 4
        }
        
        gap_size = interval_gaps.get(instance.generation_mode, 0)
        workday_counter = 0  # Tracks working days sequentially (ignoring Sat/Sun)

        # Pre-calculate a rolling 60-day path
        for i in range(60):
            current_date = start_date + datetime.timedelta(days=i)
            day_str = current_date.strftime('%A')
            
            # STRICT RULE: Skip weekends entirely from logic
            if day_str in ['Saturday', 'Sunday']:
                continue
                
            mode = 'REMOTE'
            
            # LOGIC 1: CONSTANT LOCKED DAYS
            if instance.generation_mode == 'CONSTANT':
                if day_str == 'Monday' and instance.constant_monday: mode = 'PHYSICAL'
                elif day_str == 'Tuesday' and instance.constant_tuesday: mode = 'PHYSICAL'
                elif day_str == 'Wednesday' and instance.constant_wednesday: mode = 'PHYSICAL'
                elif day_str == 'Thursday' and instance.constant_thursday: mode = 'PHYSICAL'
                elif day_str == 'Friday' and instance.constant_friday: mode = 'PHYSICAL'
                
            # LOGIC 2: ROLLING WORKDAY INTERVAL GAPS
            else:
                # On-Site hits whenever the workday counter hits 0 after completing a gap cycle
                if workday_counter % (gap_size + 1) == 0:
                    mode = 'PHYSICAL'
                workday_counter += 1

            shifts_to_create.append(
                GeneratedShift(
                    attachee=attachee,
                    date=current_date,
                    day_name=day_str,
                    work_mode=mode
                )
            )
            
        GeneratedShift.objects.bulk_create(shifts_to_create)
